---

version: '3'

services:
  eventstore:
    image:
      eventstore/eventstore:release-4.1.1-hotfix1
    environment:
      - "EVENTSTORE_DB=${EVENTSTORE_DB}"
      - "EVENTSTORE_DISABLE_HTTP_CACHING=${EVENTSTORE_DISABLE_HTTP_CACHING}"
      - "EVENTSTORE_EXT_IP=${EVENTSTORE_EXT_IP}"
      - "EVENTSTORE_EXT_HTTP_PORT=${EVENTSTORE_EXT_HTTP_PORT}"
      - "EVENTSTORE_EXT_HTTP_PREFIXES=${EVENTSTORE_EXT_HTTP_PREFIXES}"
      - "EVENTSTORE_EXT_TCP_PORT=${EVENTSTORE_EXT_TCP_PORT}"
      - "EVENTSTORE_EXT_TCP_HEARTBEAT_TIMEOUT=${EVENTSTORE_EXT_TCP_HEARTBEAT_TIMEOUT}"
      - "EVENTSTORE_INT_HTTP_PORT=${EVENTSTORE_INT_HTTP_PORT}"
      - "EVENTSTORE_INT_TCP_PORT=${EVENTSTORE_INT_TCP_PORT}"
      - "EVENTSTORE_LOG=${EVENTSTORE_LOG}"
      - "EVENTSTORE_MEM_DB=${EVENTSTORE_MEM_DB}"
      - "EVENTSTORE_RUN_PROJECTIONS=${EVENTSTORE_RUN_PROJECTIONS}"
      - "EVENTSTORE_SCAVENGE_HISTORY_MAX_AGE=${EVENTSTORE_SCAVENGE_HISTORY_MAX_AGE}"
      - "EVENTSTORE_SKIP_DB_VERIFY=${EVENTSTORE_SKIP_DB_VERIFY}"
      - "EVENTSTORE_START_STANDARD_PROJECTIONS=${EVENTSTORE_START_STANDARD_PROJECTIONS}"
    ports:
      - "${EVENTSTORE_EXT_HTTP_PORT}:${EVENTSTORE_EXT_HTTP_PORT}"
      - "${EVENTSTORE_EXT_TCP_PORT}:${EVENTSTORE_EXT_TCP_PORT}"
    expose:
      - "${EVENTSTORE_EXT_HTTP_PORT}"
      - "${EVENTSTORE_EXT_TCP_PORT}"
    healthcheck:
      interval: 10s
      retries: 10
      test: ["CMD", "curl", "-sf", "http://localhost:${EVENTSTORE_EXT_HTTP_PORT}/stats"]
      timeout: 2s
    restart: always
  app:
    build:
      context: ./app/
    environment:
      - "EVENTSTORE_URL=http://eventstore:${EVENTSTORE_EXT_HTTP_PORT}/"
      - "EVENTSTORE_USER=admin"
      - "EVENTSTORE_PASS=changeit"
